# gosqlpp MCP Server Configuration

server:
  # Transport mode: "stdio" for direct MCP client communication, "http" for HTTP+SSE
  transport: "http"
  # HTTP server configuration (only used when transport is "http")
  host: "localhost"
  port: 8080

sqlpp:
  # Path to the sqlpp executable
  # Can be absolute path or command name if in PATH
  executable_path: "../gosqlpp/sqlpp"
  # Timeout for sqlpp operations in seconds
  timeout: 300

log:
  # Log level: trace, debug, info, warn, error, fatal, panic
  level: "info"
  # Log format: "text" or "json"
  format: "text"

aws:
  # Default AWS region for deployment
  region: "us-east-1"
  # Environment name (development, test, production)
  environment: "development"
