# Test configuration with file logging enabled
server:
  transport: "stdio"
  host: "localhost"
  port: 8080

sqlpp:
  executable_path: "../gosqlpp/sqlpp"
  timeout: 300

log:
  level: "trace"
  format: "json"
  file_logging: true

aws:
  region: "us-east-1"
  environment: "test"
